### ISSUE TITLE
After downloading all zippyshare files from one dlc zippyshare-downloader does not quit automatically

### ISSUE THREAD

**Issue by ghost** [AlexanderProd/zippyshare-downloader#1]
Hi,

after downloading all zippyshare files from one dlc file zippyshare-downloader does not quit automatically. I have to CTRL + C to kill the process.

Could you fix that please, or what could I do to that it quits automatically?

Thanks.

Regards

**Comment by AlexanderProd** [comment]
Hi,

Unfortunately I can't use the package myself anymore because Zippyshare geoblocks all requests from my country (Germany), so I can only guess what could be the problem. Afaik the problem is that the node process stays active even after the batch script has finished already, so you'd have to call `process.exit()` once the shell process returns.

**Comment by ghost** [comment]
OK thanks for help, maybe it works with this method.
